name: Update calendar

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Update calendar

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: fedora-python/python-release-schedule-ical
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: pipenv install
    - name: Run script
      run: pipenv run update-calendar
    - if: github.event_name == 'schedule'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Auto commit - Calendar was updated

